version: "3"

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
  app: 
    build: 
      context: App
    container_name: node-app
    networks: 
      - node-network
    volumes: 
      - ./App:/usr/src/app
    tty: true
    depends_on: 
      - db
  nginx: 
    build:
      context: nginx
    container_name: nginx-frontend
    ports:
      - 8080:80
    networks:
      - node-network
    depends_on: 
      - app

networks:
  node-network:
    driver: bridge
